// Auto-generated by TanStack Router when running `vinxi dev`
// Do not edit manually — this file is overwritten on every dev server start
import { Route as rootRoute } from "./routes/__root";

export const routeTree = rootRoute;
